version: "3.8"
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  devcontainer:
    image: ghcr.io/studitemps/devcontainer-base:date-2024-09-04

    environment:
      - DOPPLER_TOKEN

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      - /var/run/docker.sock:/var/run/docker.sock
      # Store command history persistently
      - commandhistory:/commandhistory
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
volumes:
  commandhistory:
